# Generated by Django 3.0.5 on 2020-09-09 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200909_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categpry',
            new_name='category',
        ),
    ]
